#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: Apache-2.0

START=99
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/domain-limit daemon
	procd_set_param respawn 3600 5 5
	procd_set_param reload_signal USR1
	procd_set_param term_timeout 20
	procd_close_instance
}

reload_service() {
	if ubus call service list '{"name":"domain-limit"}' 2>/dev/null | grep -q '"running": true'; then
		procd_send_signal domain-limit
	else
		start
	fi
}

stop_service() {
	/usr/sbin/domain-limit stop
}

service_triggers() {
	procd_add_reload_trigger "domain-limit"
}
